Detect nil attributes at runtime
weavejester/hiccup pull request #208
Opened 2023-12-14 15:55 UTC by luontola

Before this change `(html [:br (identity nil)])` used to produced `"<br></br>"`. After this change it will produce `"<br />"`.

The use case where this can matter is if the user has a function which returns either a map of attributes or nil.

2023-12-18 18:05 UTC, weavejester requested changes
Some very minor formatting suggestions. Could you also ensure the commit message uses plaintext rather than markdown formatting. So something like:

```
Fix formatting of nil attributes at runtime

Fix forms like (html [:br (identity nil)]) to produce "<br />" or "<br>"
rather than "<br></br>".
```

2023-12-18 18:06 UTC, weavejester commented
Thanks for the fix! And apologies for taking a little while to take a closer look.

2023-12-21 12:08 UTC, luontola commented
Changes done.

2024-01-05 17:07 UTC, luontola commented
@weavejester This too is ready

2024-01-09 02:49 UTC, merged